# Generated by Django 5.2.14 on 2026-05-29 09:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('author', 'Author'), ('client', 'Client'), ('freelancer', 'Freelancer')], default='author', max_length=20, verbose_name='User Role')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Profile Picture')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Bio')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone Number')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified Account')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=200, verbose_name='Professional Headline')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='Skills')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hourly Rate (₹)')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfolio URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X URL')),
                ('rating', models.FloatField(default=0.0, verbose_name='Average Rating')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='Total Reviews')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Earnings (₹)')),
                ('total_projects', models.IntegerField(default=0, verbose_name='Completed Projects')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available for Hire')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
