# Generated by Django 5.2.14 on 2026-06-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('author', 'Author'), ('client', 'Client'), ('freelancer', 'Freelancer')], default='client', max_length=20, verbose_name='User Role'),
        ),
    ]
