# Generated by Django 5.2.14 on 2026-05-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='project_live_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Live URL'),
        ),
        migrations.AddField(
            model_name='post',
            name='project_price',
            field=models.CharField(blank=True, help_text='e.g., "$500", "Starting at $1000", "Fixed"', max_length=100, null=True, verbose_name='Project Price'),
        ),
    ]
