# Generated by Django 5.2.14 on 2026-06-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postseries_post_series_order_post_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_project',
            field=models.BooleanField(default=False, verbose_name='Is Portfolio Project'),
        ),
    ]
