# Generated by Django 5.2.14 on 2026-06-21 08:59

from django.db import migrations


def update_existing_projects(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    # Update posts that have the portfolio category
    Post.objects.filter(category__slug='portfolio').update(is_project=True)
    # Update posts that have a project_live_url or project_price
    Post.objects.exclude(project_live_url='').update(is_project=True)
    Post.objects.exclude(project_price='').update(is_project=True)

def reverse_update(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_is_project'),
    ]

    operations = [
        migrations.RunPython(update_existing_projects, reverse_update),
    ]
