# Generated by Django 5.2.14 on 2026-06-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_set_existing_projects'),
    ]

    operations = [
    ]
